//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasPrimaryLinkItemId")]
        public string arasPrimaryLinkItemId {
            get {
                return ((string)(this["arasPrimaryLinkItemId"]));
            }
            set {
                this["arasPrimaryLinkItemId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("url")]
        public string ArasURL {
            get {
                return ((string)(this["ArasURL"]));
            }
            set {
                this["ArasURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db")]
        public string ARASdb {
            get {
                return ((string)(this["ARASdb"]));
            }
            set {
                this["ARASdb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ArasInfo")]
        public string ArasInfoNodeName {
            get {
                return ((string)(this["ArasInfoNodeName"]));
            }
            set {
                this["ArasInfoNodeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow\" action=\"get\"></Item></AML>")]
        public string getWorkFlowAML {
            get {
                return ((string)(this["getWorkFlowAML"]));
            }
            set {
                this["getWorkFlowAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow Process\" action=\"get\"></Item></AML>")]
        public string getWorkFlowProcessAML {
            get {
                return ((string)(this["getWorkFlowProcessAML"]));
            }
            set {
                this["getWorkFlowProcessAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow Map\" action=\"get\" select=\"name\"></Item></AML>")]
        public string getWorkflowMapNameAML {
            get {
                return ((string)(this["getWorkflowMapNameAML"]));
            }
            set {
                this["getWorkflowMapNameAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow Process Activity\" action=\"get\" select=\"related_id\"></It" +
            "em></AML>")]
        public string getActivitiesAML {
            get {
                return ((string)(this["getActivitiesAML"]));
            }
            set {
                this["getActivitiesAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Activity Task\" action=\"get\" select=\"sequence,is_required,descrip" +
            "tion\"></Item></AML>")]
        public string getTasksAML {
            get {
                return ((string)(this["getTasksAML"]));
            }
            set {
                this["getTasksAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow Process Path\" action=\"get\"></Item></AML>")]
        public string getVotePaths {
            get {
                return ((string)(this["getVotePaths"]));
            }
            set {
                this["getVotePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Activity Assignment\" action=\"get\"></Item></AML>")]
        public string getActivityAssignement {
            get {
                return ((string)(this["getActivityAssignement"]));
            }
            set {
                this["getActivityAssignement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"User\" action=\"get\" select=\"owned_by_id\"></Item></AML>")]
        public string getLoggedInIdentityID {
            get {
                return ((string)(this["getLoggedInIdentityID"]));
            }
            set {
                this["getLoggedInIdentityID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Document\" action=\"get\" select=\"state,current_state\"></Item></AML" +
            ">")]
        public string getStateName {
            get {
                return ((string)(this["getStateName"]));
            }
            set {
                this["getStateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasDocumentId")]
        public string ArasDocumentId {
            get {
                return ((string)(this["ArasDocumentId"]));
            }
            set {
                this["ArasDocumentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Life Cycle Map\" action=\"get\" select=\"description\"><Relationships" +
            "><Item type=\"Life Cycle State\" action=\"get\"><id></id></Item></Relationships></It" +
            "em></AML>")]
        public string getLifeCycleName {
            get {
                return ((string)(this["getLifeCycleName"]));
            }
            set {
                this["getLifeCycleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Document\" action=\"promoteItem\" where=\"document.id=></Item></AML>" +
            "")]
        public string promoteAML {
            get {
                return ((string)(this["promoteAML"]));
            }
            set {
                this["promoteAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Identity\" action=\"GetCurrentUserIdentities\"></Item></AML>")]
        public string getCurrentUserIDs {
            get {
                return ((string)(this["getCurrentUserIDs"]));
            }
            set {
                this["getCurrentUserIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Life Cycle Transition\" action=\"get\" ></Item></AML>")]
        public string getNextStates {
            get {
                return ((string)(this["getNextStates"]));
            }
            set {
                this["getNextStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasDocumentConfigId")]
        public string ArasConfigId {
            get {
                return ((string)(this["ArasConfigId"]));
            }
            set {
                this["ArasConfigId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"InBasket Task\" action=\"get\">\r\n<status condition=\"eq\">Active</s" +
            "tatus>\r\n  <my_assignment condition=\"eq\">1</my_assignment>\r\n  </Item>\r\n</AML>")]
        public string getMyTasks {
            get {
                return ((string)(this["getMyTasks"]));
            }
            set {
                this["getMyTasks"] = value;
            }
        }
    }
}
